In [3]:
import os
import sys
import numpy as np

def path_link(path:str):
    sys.path.append(path)

path_link('../code/lib')

import features as ft
import simulation as sim 

### Global variables

In [2]:
print(f'NB_HIST >>>>> {ft.NB_HIST}')
print(f'THRESHOLD_DIST >>>>> {ft.THRESHOLD_DIST}')
print(f'NUMBER_ROLLOUT >>>>> {ft.NUMBER_ROLLOUT}')
print(f'FEATURE_SHAPE >>>>> {ft.FEATURE_SHAPE}')
print(f'EDGE_SHAPE >>>>> {ft.EDGE_SHAPE}')
print(f'MIN_DIST >>>>> {ft.MIN_DIST}')
print(f'MAX_DIST >>>>> {ft.MAX_DIST}')
print(f'MIN_X >>>>> {ft.MIN_X}')
print(f'MAX_X >>>>> {ft.MAX_X}')
print(f'MIN_Y >>>>> {ft.MIN_Y}')
print(f'MAX_Y >>>>> {ft.MAX_Y}')

NB_HIST >>>>> 4
THRESHOLD_DIST >>>>> 6
NUMBER_ROLLOUT >>>>> 10
FEATURE_SHAPE >>>>> 17
EDGE_SHAPE >>>>> 3
MIN_DIST >>>>> 0
MAX_DIST >>>>> 6
MIN_X >>>>> -120
MAX_X >>>>> 120
MIN_Y >>>>> -120
MAX_Y >>>>> 120


### =======

### Force expression

### Testing the features

In [27]:
# generate a simulation
data = sim.compute_main(100, (70, 5.5, 3.4, 0.4), 120)[0]

# get speeds
v = ft.getSpeeds(data)

mat = ft.getFeatures(data, np.array([0.1]))

featuresData = mat[0]

nextState = mat[1]

v0:70, tau:5.5, k:3.4, epsilon:0.4


100%|██████████| 100/100 [00:01<00:00, 86.11it/s]


In [28]:
print(data[:,0,:])

[[ -8.15599412  -5.92841253]
 [ -7.8821651   -6.53049684]
 [ -7.62863066  -7.12378241]
 [ -7.35213207  -7.68481874]
 [ -6.97965432  -8.30145637]
 [ -6.67204638  -8.87935115]
 [ -6.36155527  -9.47305893]
 [ -6.12805555 -10.04636603]
 [ -5.79903269 -10.64766281]
 [ -5.47457307 -11.22717966]
 [ -5.14763267 -11.83332985]
 [ -4.83080935 -12.40862511]
 [ -4.51845629 -12.98583992]
 [ -4.1901708  -13.59646429]
 [ -3.88837984 -14.20882505]
 [ -3.61165207 -14.87740479]
 [ -3.27918525 -15.55265563]
 [ -2.95227141 -16.18078598]
 [ -2.65172114 -16.79301921]
 [ -2.30851585 -17.42703372]
 [ -1.98890257 -18.04980763]
 [ -1.66928928 -18.67258154]
 [ -1.349676   -19.29535546]
 [ -1.03006272 -19.91812937]
 [ -0.71044943 -20.54090329]
 [ -0.39083615 -21.1636772 ]
 [ -0.07122287 -21.78645112]
 [  0.24839042 -22.40922503]
 [  0.5680037  -23.03199895]
 [  0.88761698 -23.65477286]
 [  1.20723027 -24.27754678]
 [  1.52684355 -24.90032069]
 [  1.84645683 -25.52309461]
 [  2.16607012 -26.14586852]
 [  2.4856834 

In [29]:
for i in range(10):
    print(featuresData[i][0])

tensor([ 0.2738, -0.6021,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.1000])
tensor([ 0.2535, -0.5933,  0.2738, -0.6021,  0.0000,  0.0000,  0.0000,  0.0000,
         0.1000])
tensor([ 0.2765, -0.5610,  0.2535, -0.5933,  0.2738, -0.6021,  0.0000,  0.0000,
         0.1000])
tensor([ 0.3725, -0.6166,  0.2765, -0.5610,  0.2535, -0.5933,  0.2738, -0.6021,
         0.1000])
tensor([ 0.3076, -0.5779,  0.3725, -0.6166,  0.2765, -0.5610,  0.2535, -0.5933,
         0.1000])
tensor([ 0.3105, -0.5937,  0.3076, -0.5779,  0.3725, -0.6166,  0.2765, -0.5610,
         0.1000])
tensor([ 0.2335, -0.5733,  0.3105, -0.5937,  0.3076, -0.5779,  0.3725, -0.6166,
         0.1000])
tensor([ 0.3290, -0.6013,  0.2335, -0.5733,  0.3105, -0.5937,  0.3076, -0.5779,
         0.1000])
tensor([ 0.3245, -0.5795,  0.3290, -0.6013,  0.2335, -0.5733,  0.3105, -0.5937,
         0.1000])
tensor([ 0.3269, -0.6062,  0.3245, -0.5795,  0.3290, -0.6013,  0.2335, -0.5733,
         0.1000])


### =======

### Edges

In [30]:
edge_ind, edge_atr = ft.getEdges(data)

In [36]:
print(edge_atr[50])

tensor([[ 0.5814, -3.4112,  0.7299],
        [ 0.5802, -3.0714,  1.6382],
        [ 0.8022, -4.4251,  1.8942],
        [ 0.4674,  1.3533,  2.4564],
        [ 0.2059, -1.0834,  0.5938],
        [ 0.4405,  2.1890, -1.4814],
        [ 0.2472,  0.8353, -1.2255],
        [ 0.7749, -1.5385, -4.3874],
        [ 0.5141, -2.4800,  1.8340],
        [ 0.2985, -0.1129, -1.7876],
        [ 0.4564,  2.6836,  0.5460],
        [ 0.6521,  2.7107,  2.8217],
        [ 0.7359, -0.7982,  4.3425],
        [ 0.7057, -1.7614, -3.8503],
        [ 0.4752, -2.7443, -0.7725],
        [ 0.3347, -0.1311,  2.0037],
        [ 0.8301,  4.7441,  1.5174],
        [ 0.3477,  1.2644, -1.6596],
        [ 0.8692, -4.0264, -3.3143],
        [ 0.7412, -2.2200, -3.8535],
        [ 0.6354,  2.6132,  2.7761],
        [ 0.6718, -2.4779, -3.1791],
        [ 0.2951, -0.3747,  1.7308],
        [ 0.2679, -0.1831,  1.5972],
        [ 0.3752, -1.9866,  1.0595],
        [ 0.6021, -3.4020, -1.2152],
        [ 0.8264, -3.5479,  3.4641],
 

In [45]:
d = {}

for i in range(len(edge_ind[80][0])):
    if edge_ind[80][0, i].item() not in d:
        d[edge_ind[80][0, i].item()] = {}
    d[edge_ind[80][0, i].item()][edge_ind[80][1, i].item()] = edge_atr[80][i]
    #print(f'{edge_ind[80][0, i].item()} ---- {edge_ind[80][1, i].item()}')

In [50]:
print(d[1])
print(d[17])
print(d[92])

{17: tensor([ 0.5721, -0.4936,  3.3969]), 92: tensor([ 0.9019, -0.3360,  5.4007])}
{92: tensor([0.3350, 0.1576, 2.0039]), 1: tensor([ 0.5721,  3.3969, -0.4936]), 4: tensor([ 0.5749, -3.3533,  0.8082])}
{1: tensor([ 0.9019,  5.4007, -0.3360]), 4: tensor([ 0.2766, -1.3495,  0.9658]), 17: tensor([0.3350, 2.0039, 0.1576]), 33: tensor([ 0.8419, -4.8117, -1.5384])}
