In [1]:
import os
import sys
import numpy as np
import matplotlib.pyplot as plt

def path_link(path:str):
    sys.path.append(path)

path_link('master/code/lib')

import features as ft
import simulation as sim 
import display as disp

yessss


### Global variables

In [2]:
print(f'NB_HIST >>>>> {ft.NB_HIST}')
print(f'THRESHOLD_DIST >>>>> {ft.THRESHOLD_DIST}')
print(f'NUMBER_ROLLOUT >>>>> {ft.NUMBER_ROLLOUT}')
print(f'FEATURE_SHAPE >>>>> {ft.FEATURE_SHAPE}')
print(f'EDGE_SHAPE >>>>> {ft.EDGE_SHAPE}')
print(f'MIN_DIST >>>>> {ft.MIN_DIST}')
print(f'MAX_DIST >>>>> {ft.MAX_DIST}')
print(f'MIN_X >>>>> {ft.MIN_X}')
print(f'MAX_X >>>>> {ft.MAX_X}')
print(f'MIN_Y >>>>> {ft.MIN_Y}')
print(f'MAX_Y >>>>> {ft.MAX_Y}')

NB_HIST >>>>> 4
THRESHOLD_DIST >>>>> 6
NUMBER_ROLLOUT >>>>> 10
FEATURE_SHAPE >>>>> 9
EDGE_SHAPE >>>>> 3
MIN_DIST >>>>> 0
MAX_DIST >>>>> 6
MIN_X >>>>> -120
MAX_X >>>>> 120
MIN_Y >>>>> -120
MAX_Y >>>>> 120


### =======

### Force expression

### Testing the features

In [3]:
# generate a simulation
data = sim.compute_main(100, (60, 3.5, 70, 0.5), 120, T = 1000)[0]

# get speeds
v = ft.getSpeeds(data)

mat = ft.getFeatures(data, np.array([0.1]))

featuresData = mat[0]

nextState = mat[1]

v0:60, tau:3.5, k:70, epsilon:0.5


100%|██████████| 1000/1000 [00:03<00:00, 325.57it/s]


In [8]:
print(data[:,0,:])

[[-8.15731740e+00 -6.47553260e+00]
 [-8.23111945e+00 -7.57543103e+00]
 [-7.49915580e+00 -8.54118601e+00]
 [-5.39379784e+00 -9.18185712e+00]
 [-5.61475240e+00 -1.16135629e+01]
 [-6.70769103e+00 -1.20447869e+01]
 [-6.45658512e+00 -1.18311370e+01]
 [-5.41538971e+00 -1.29339339e+01]
 [-4.77053493e+00 -1.32273075e+01]
 [-4.99634565e+00 -1.41907413e+01]
 [-4.71356876e+00 -1.55012668e+01]
 [-4.17094654e+00 -1.65852435e+01]
 [-3.64234584e+00 -1.67583227e+01]
 [-2.10983131e+00 -1.81786470e+01]
 [-1.93504693e+00 -1.88116733e+01]
 [-1.76231760e+00 -1.94503155e+01]
 [-1.90106337e+00 -2.03921406e+01]
 [-2.27947012e+00 -2.15497896e+01]
 [-2.00096558e+00 -2.20790297e+01]
 [-1.66316152e+00 -2.31914826e+01]
 [-1.56373540e+00 -2.39096105e+01]
 [-1.47748823e+00 -2.46637587e+01]
 [-1.38473935e+00 -2.54374918e+01]
 [-1.35133677e+00 -2.61214720e+01]
 [-1.28103314e+00 -2.67923908e+01]
 [-1.20847826e+00 -2.74722510e+01]
 [-1.13615755e+00 -2.81641748e+01]
 [-1.06338890e+00 -2.88694456e+01]
 [-9.88956841e-01 -2

In [9]:
for i in range(10):
    print(featuresData[i][0])

tensor([-0.0738, -1.0999,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.1000])
tensor([ 0.7320, -0.9658, -0.0738, -1.0999,  0.0000,  0.0000,  0.0000,  0.0000,
         0.1000])
tensor([ 2.1054, -0.6407,  0.7320, -0.9658, -0.0738, -1.0999,  0.0000,  0.0000,
         0.1000])
tensor([-0.2210, -2.4317,  2.1054, -0.6407,  0.7320, -0.9658, -0.0738, -1.0999,
         0.1000])
tensor([-1.0929, -0.4312, -0.2210, -2.4317,  2.1054, -0.6407,  0.7320, -0.9658,
         0.1000])
tensor([ 0.2511,  0.2136, -1.0929, -0.4312, -0.2210, -2.4317,  2.1054, -0.6407,
         0.1000])
tensor([ 1.0412, -1.1028,  0.2511,  0.2136, -1.0929, -0.4312, -0.2210, -2.4317,
         0.1000])
tensor([ 0.6449, -0.2934,  1.0412, -1.1028,  0.2511,  0.2136, -1.0929, -0.4312,
         0.1000])
tensor([-0.2258, -0.9634,  0.6449, -0.2934,  1.0412, -1.1028,  0.2511,  0.2136,
         0.1000])
tensor([ 0.2828, -1.3105, -0.2258, -0.9634,  0.6449, -0.2934,  1.0412, -1.1028,
         0.1000])


In [33]:
t = 6
print(featuresData[t+1][0])
print(nextState[t][0])

tensor([ 0.6449, -0.2934,  1.0412, -1.1028,  0.2511,  0.2136, -1.0929, -0.4312,
         0.1000])
tensor([ 0.6449, -0.2934, -0.2258, -0.9634,  0.2828, -1.3105,  0.5426, -1.0840,
         0.5286, -0.1731,  1.5325, -1.4203,  0.1748, -0.6330,  0.1727, -0.6386,
        -0.1387, -0.9418, -0.3784, -1.1576], dtype=torch.float64)


### =======

### Edges

In [4]:
edge_ind, edge_atr = ft.getEdges(data)

In [35]:
print(edge_atr[50])

tensor([[ 0.6723,  4.0185, -0.3515],
        [ 0.3247, -1.9477,  0.0455],
        [ 0.3897,  2.0053,  1.2028],
        [ 0.8870,  3.5180, -3.9931],
        [ 0.4945,  1.1249, -2.7452],
        [ 0.9801,  2.1404, -5.4772],
        [ 0.7082,  0.5895, -4.2083],
        [ 0.9321,  1.0803,  5.4874],
        [ 0.3943,  1.9608,  1.3240],
        [ 0.9882,  4.9523, -3.2607],
        [ 0.4077,  2.3038,  0.8229],
        [ 0.9691,  4.6598, -3.4778],
        [ 0.4375, -2.6062, -0.3117],
        [ 0.8200,  2.3939, -4.2982],
        [ 0.7378,  3.5193, -2.6855],
        [ 0.7539, -1.8208, -4.1405],
        [ 0.9815,  5.2771, -2.6138],
        [ 0.7960,  4.7647, -0.3310],
        [ 0.3931,  0.2931, -2.3402],
        [ 0.4438, -1.9463, -1.8168],
        [ 0.4292,  0.2800, -2.5597],
        [ 0.3528, -1.0778, -1.8220],
        [ 0.4517, -2.6399,  0.6134],
        [ 0.7353, -4.1689, -1.4431],
        [ 0.4050, -1.2918,  2.0584],
        [ 0.9499,  1.3712,  5.5322],
        [ 0.7441,  4.3627,  0.9476],
 

In [ ]:
d = {}

for i in range(len(edge_ind[80][0])):
    if edge_ind[80][0, i].item() not in d:
        d[edge_ind[80][0, i].item()] = {}
    d[edge_ind[80][0, i].item()][edge_ind[80][1, i].item()] = edge_atr[80][i]
    #print(f'{edge_ind[80][0, i].item()} ---- {edge_ind[80][1, i].item()}')

In [50]:
print(d[1])
print(d[17])
print(d[92])

{17: tensor([ 0.5721, -0.4936,  3.3969]), 92: tensor([ 0.9019, -0.3360,  5.4007])}
{92: tensor([0.3350, 0.1576, 2.0039]), 1: tensor([ 0.5721,  3.3969, -0.4936]), 4: tensor([ 0.5749, -3.3533,  0.8082])}
{1: tensor([ 0.9019,  5.4007, -0.3360]), 4: tensor([ 0.2766, -1.3495,  0.9658]), 17: tensor([0.3350, 2.0039, 0.1576]), 33: tensor([ 0.8419, -4.8117, -1.5384])}


In [7]:
print(len(edge_ind))

109


In [8]:
print(data.shape)

(120, 100, 2)


In [12]:
print(data)

[[[ -8.1573174   -6.4755326 ]
  [  9.66396793  -2.96524812]
  [  8.8131778   -4.51966391]
  ...
  [ -9.40695045  -5.68911859]
  [  1.82371428 -11.02456058]
  [ -9.50501506   2.64205487]]

 [[ -8.23111945  -7.57543103]
  [ 10.29463228  -2.13951389]
  [  8.08164686  -3.15661685]
  ...
  [ -9.16921477  -6.52926535]
  [  1.70224    -12.78473246]
  [ -9.65795068   2.69743454]]

 [[ -7.4991558   -8.54118601]
  [ 10.71210177  -1.09801078]
  [  7.18703901  -2.58231467]
  ...
  [-10.98964132  -7.68072485]
  [  2.36723656 -12.55471017]
  [ -8.44844697   1.99139034]]

 ...

 [[ 17.64363798 -84.57634829]
  [-21.22286403  50.01129792]
  [-32.70304755  54.27179529]
  ...
  [-82.23341353 -21.62254706]
  [-42.47680639 -83.14371915]
  [ 60.61757732  -4.57925471]]

 [[ 17.81382161 -85.15716645]
  [-21.46799756  50.53622772]
  [-33.06884043  54.74739552]
  ...
  [-82.83627426 -21.6840824 ]
  [-42.83599249 -83.6321949 ]
  [ 61.20863249  -4.68247189]]

 [[ 17.98400442 -85.7379854 ]
  [-21.7131311   51.0611

In [6]:
attr, ind = ft.optimized_getGraph(data[0, :, :])
inds2, attr2 = ft.getGraph1(data[0, :, :])

In [17]:
d1 = {}
for i in range(ind.shape[1]):
    d1[f'{ind[0, i]}-{ind[1, i]}'] = attr[i, :]

In [18]:
d2 = {}
for i in range(inds2.shape[1]):
    d2[f'{inds2[0, i]}-{inds2[1, i]}'] = attr2[i, :]

In [23]:
import torch

In [25]:
print(d1)

{'0-5': tensor([ 3.5655,  0.6360, -0.7717]), '0-7': tensor([ 2.5597, -0.8277,  0.5612]), '0-8': tensor([ 2.9317,  0.8925, -0.4510]), '0-22': tensor([7.1140e-01, 1.9531e-04, 1.0000e+00]), '0-26': tensor([ 1.4965,  0.7949, -0.6067]), '0-30': tensor([ 5.6844,  0.7418, -0.6706]), '0-31': tensor([ 4.0759,  0.5497, -0.8354]), '0-35': tensor([ 5.3382, -0.2038,  0.9790]), '0-40': tensor([1.6454, 0.9520, 0.3062]), '0-41': tensor([ 3.0857, -0.2058,  0.9786]), '0-45': tensor([ 1.6789, -0.0074,  1.0000]), '0-47': tensor([ 1.2884, -0.9795, -0.2015]), '0-55': tensor([ 2.1907, -0.4198,  0.9076]), '0-57': tensor([ 1.3523,  0.1912, -0.9815]), '0-63': tensor([ 2.0589,  0.8802, -0.4746]), '0-68': tensor([ 4.7081, -0.4899,  0.8718]), '0-70': tensor([ 1.4428,  0.9662, -0.2576]), '0-76': tensor([ 3.1246, -0.4879,  0.8729]), '0-77': tensor([ 5.3349,  0.8127, -0.5827]), '0-79': tensor([1.5609, 0.6786, 0.7345]), '0-81': tensor([ 4.7593,  0.9883, -0.1528]), '0-95': tensor([ 4.1574, -0.3010,  0.9536]), '0-97': t

In [29]:
print(d1['0-5'])
print(d1['5-0'])

tensor([ 3.5655,  0.6360, -0.7717])
tensor([ 3.5655, -0.6360,  0.7717])


In [28]:
for k in d1.keys():
    print(d1[k])
    print(d2[k])
    print('----')

tensor([ 3.5655,  0.6360, -0.7717])
tensor([ 3.5655,  0.6360, -0.7717])
----
tensor([ 2.5597, -0.8277,  0.5612])
tensor([ 2.5597, -0.8277,  0.5612])
----
tensor([ 2.9317,  0.8925, -0.4510])
tensor([ 2.9317,  0.8925, -0.4510])
----
tensor([7.1140e-01, 1.9531e-04, 1.0000e+00])
tensor([7.1140e-01, 1.9531e-04, 1.0000e+00])
----
tensor([ 1.4965,  0.7949, -0.6067])
tensor([ 1.4965,  0.7949, -0.6067])
----
tensor([ 5.6844,  0.7418, -0.6706])
tensor([ 5.6844,  0.7418, -0.6706])
----
tensor([ 4.0759,  0.5497, -0.8354])
tensor([ 4.0759,  0.5497, -0.8354])
----
tensor([ 5.3382, -0.2038,  0.9790])
tensor([ 5.3382, -0.2038,  0.9790])
----
tensor([1.6454, 0.9520, 0.3062])
tensor([1.6454, 0.9520, 0.3062])
----
tensor([ 3.0857, -0.2058,  0.9786])
tensor([ 3.0857, -0.2058,  0.9786])
----
tensor([ 1.6789, -0.0074,  1.0000])
tensor([ 1.6789, -0.0074,  1.0000])
----
tensor([ 1.2884, -0.9795, -0.2015])
tensor([ 1.2884, -0.9795, -0.2015])
----
tensor([ 2.1907, -0.4198,  0.9076])
tensor([ 2.1907, -0.4198,  0

In [24]:
for k in d1.keys():
    if torch.sum(d1[k] - d2[k]) > 0:
        print('aie')


In [4]:
import torch
cwd = os.getcwd()
p = '/master/tests/data/graph.mp4'
vidParams = disp.videoParameters(p)
edge_inds, edge_atrs = [], []

for i in range(data.shape[0]):
    attr, ind = ft.optimized_getGraph(data[i, :, :])
    edge_inds.append(ind)
    edge_atrs.append(attr)

disp.videoGraphBase(torch.from_numpy(data.copy()), edge_inds, vidParams, bounds=((-140, 140), (-140, 140)))

In [14]:
print(edge_inds)

[tensor([[ 0,  0,  0,  ..., 96, 97, 99],
        [ 5,  7,  8,  ..., 94, 95, 95]]), tensor([[ 0,  0,  0,  ..., 96, 97, 99],
        [ 5,  8, 17,  ..., 94, 95, 95]]), tensor([[ 0,  0,  0,  ..., 96, 97, 99],
        [ 5,  8, 17,  ..., 94, 95, 95]]), tensor([[ 0,  0,  0,  ..., 96, 97, 99],
        [ 5,  8, 11,  ..., 94, 95, 95]]), tensor([[ 0,  0,  0,  ..., 96, 96, 97],
        [ 3,  5, 17,  ..., 91, 94, 95]]), tensor([[ 0,  0,  0,  ..., 96, 96, 97],
        [ 3,  5, 17,  ..., 91, 94, 95]]), tensor([[ 0,  0,  0,  ..., 98, 96, 96],
        [ 3,  5, 24,  ..., 90, 91, 94]]), tensor([[ 0,  0,  0,  ..., 98, 96, 96],
        [ 3,  5, 24,  ..., 90, 91, 94]]), tensor([[ 0,  0,  0,  ..., 98, 99, 96],
        [ 3,  5, 24,  ..., 90, 92, 94]]), tensor([[ 0,  0,  0,  ..., 98, 99, 96],
        [ 3,  5, 24,  ..., 90, 92, 94]]), tensor([[ 0,  0,  0,  ..., 98, 99, 96],
        [ 3,  5, 24,  ..., 90, 92, 94]]), tensor([[ 0,  0,  0,  ..., 98, 99, 96],
        [ 3,  5, 24,  ..., 90, 92, 94]]), tensor([[ 0,  0

In [15]:
print(data)

[[[ -8.1573174   -6.4755326 ]
  [  9.66396793  -2.96524812]
  [  8.8131778   -4.51966391]
  ...
  [ -9.40695045  -5.68911859]
  [  1.82371428 -11.02456058]
  [ -9.50501506   2.64205487]]

 [[ -8.23111945  -7.57543103]
  [ 10.29463228  -2.13951389]
  [  8.08164686  -3.15661685]
  ...
  [ -9.16921477  -6.52926535]
  [  1.70224    -12.78473246]
  [ -9.65795068   2.69743454]]

 [[ -7.4991558   -8.54118601]
  [ 10.71210177  -1.09801078]
  [  7.18703901  -2.58231467]
  ...
  [-10.98964132  -7.68072485]
  [  2.36723656 -12.55471017]
  [ -8.44844697   1.99139034]]

 ...

 [[ 17.64363798 -84.57634829]
  [-21.22286403  50.01129792]
  [-32.70304755  54.27179529]
  ...
  [-82.23341353 -21.62254706]
  [-42.47680639 -83.14371915]
  [ 60.61757732  -4.57925471]]

 [[ 17.81382161 -85.15716645]
  [-21.46799756  50.53622772]
  [-33.06884043  54.74739552]
  ...
  [-82.83627426 -21.6840824 ]
  [-42.83599249 -83.6321949 ]
  [ 61.20863249  -4.68247189]]

 [[ 17.98400442 -85.7379854 ]
  [-21.7131311   51.0611