In [1]:
import os
import sys
import numpy as np
import matplotlib.pyplot as plt

def path_link(path:str):
    sys.path.append(path)

path_link('master/code/lib')

import features as ft
import simulation as sim 

### Global variables

In [2]:
print(f'NB_HIST >>>>> {ft.NB_HIST}')
print(f'THRESHOLD_DIST >>>>> {ft.THRESHOLD_DIST}')
print(f'NUMBER_ROLLOUT >>>>> {ft.NUMBER_ROLLOUT}')
print(f'FEATURE_SHAPE >>>>> {ft.FEATURE_SHAPE}')
print(f'EDGE_SHAPE >>>>> {ft.EDGE_SHAPE}')
print(f'MIN_DIST >>>>> {ft.MIN_DIST}')
print(f'MAX_DIST >>>>> {ft.MAX_DIST}')
print(f'MIN_X >>>>> {ft.MIN_X}')
print(f'MAX_X >>>>> {ft.MAX_X}')
print(f'MIN_Y >>>>> {ft.MIN_Y}')
print(f'MAX_Y >>>>> {ft.MAX_Y}')

NB_HIST >>>>> 4
THRESHOLD_DIST >>>>> 6
NUMBER_ROLLOUT >>>>> 10
FEATURE_SHAPE >>>>> 17
EDGE_SHAPE >>>>> 3
MIN_DIST >>>>> 0
MAX_DIST >>>>> 6
MIN_X >>>>> -120
MAX_X >>>>> 120
MIN_Y >>>>> -120
MAX_Y >>>>> 120


### =======

### Force expression

### Testing the features

In [7]:
# generate a simulation
data = sim.compute_main(100, (60, 3.5, 70, 0.5), 120, T = 120)[0]

# get speeds
v = ft.getSpeeds(data)

mat = ft.getFeatures(data, np.array([0.1]))

featuresData = mat[0]

nextState = mat[1]

v0:60, tau:3.5, k:70, epsilon:0.5


100%|██████████| 120/120 [00:01<00:00, 98.24it/s] 


In [8]:
print(data[:,0,:])

[[-8.15731740e+00 -6.47553260e+00]
 [-8.23111945e+00 -7.57543103e+00]
 [-7.49915580e+00 -8.54118601e+00]
 [-5.39379784e+00 -9.18185712e+00]
 [-5.61475240e+00 -1.16135629e+01]
 [-6.70769103e+00 -1.20447869e+01]
 [-6.45658512e+00 -1.18311370e+01]
 [-5.41538971e+00 -1.29339339e+01]
 [-4.77053493e+00 -1.32273075e+01]
 [-4.99634565e+00 -1.41907413e+01]
 [-4.71356876e+00 -1.55012668e+01]
 [-4.17094654e+00 -1.65852435e+01]
 [-3.64234584e+00 -1.67583227e+01]
 [-2.10983131e+00 -1.81786470e+01]
 [-1.93504693e+00 -1.88116733e+01]
 [-1.76231760e+00 -1.94503155e+01]
 [-1.90106337e+00 -2.03921406e+01]
 [-2.27947012e+00 -2.15497896e+01]
 [-2.00096558e+00 -2.20790297e+01]
 [-1.66316152e+00 -2.31914826e+01]
 [-1.56373540e+00 -2.39096105e+01]
 [-1.47748823e+00 -2.46637587e+01]
 [-1.38473935e+00 -2.54374918e+01]
 [-1.35133677e+00 -2.61214720e+01]
 [-1.28103314e+00 -2.67923908e+01]
 [-1.20847826e+00 -2.74722510e+01]
 [-1.13615755e+00 -2.81641748e+01]
 [-1.06338890e+00 -2.88694456e+01]
 [-9.88956841e-01 -2

In [9]:
for i in range(10):
    print(featuresData[i][0])

tensor([-0.0738, -1.0999,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.1000])
tensor([ 0.7320, -0.9658, -0.0738, -1.0999,  0.0000,  0.0000,  0.0000,  0.0000,
         0.1000])
tensor([ 2.1054, -0.6407,  0.7320, -0.9658, -0.0738, -1.0999,  0.0000,  0.0000,
         0.1000])
tensor([-0.2210, -2.4317,  2.1054, -0.6407,  0.7320, -0.9658, -0.0738, -1.0999,
         0.1000])
tensor([-1.0929, -0.4312, -0.2210, -2.4317,  2.1054, -0.6407,  0.7320, -0.9658,
         0.1000])
tensor([ 0.2511,  0.2136, -1.0929, -0.4312, -0.2210, -2.4317,  2.1054, -0.6407,
         0.1000])
tensor([ 1.0412, -1.1028,  0.2511,  0.2136, -1.0929, -0.4312, -0.2210, -2.4317,
         0.1000])
tensor([ 0.6449, -0.2934,  1.0412, -1.1028,  0.2511,  0.2136, -1.0929, -0.4312,
         0.1000])
tensor([-0.2258, -0.9634,  0.6449, -0.2934,  1.0412, -1.1028,  0.2511,  0.2136,
         0.1000])
tensor([ 0.2828, -1.3105, -0.2258, -0.9634,  0.6449, -0.2934,  1.0412, -1.1028,
         0.1000])


In [33]:
t = 6
print(featuresData[t+1][0])
print(nextState[t][0])

tensor([ 0.6449, -0.2934,  1.0412, -1.1028,  0.2511,  0.2136, -1.0929, -0.4312,
         0.1000])
tensor([ 0.6449, -0.2934, -0.2258, -0.9634,  0.2828, -1.3105,  0.5426, -1.0840,
         0.5286, -0.1731,  1.5325, -1.4203,  0.1748, -0.6330,  0.1727, -0.6386,
        -0.1387, -0.9418, -0.3784, -1.1576], dtype=torch.float64)


### =======

### Edges

In [34]:
edge_ind, edge_atr = ft.getEdges(data)

In [35]:
print(edge_atr[50])

tensor([[ 0.6723,  4.0185, -0.3515],
        [ 0.3247, -1.9477,  0.0455],
        [ 0.3897,  2.0053,  1.2028],
        [ 0.8870,  3.5180, -3.9931],
        [ 0.4945,  1.1249, -2.7452],
        [ 0.9801,  2.1404, -5.4772],
        [ 0.7082,  0.5895, -4.2083],
        [ 0.9321,  1.0803,  5.4874],
        [ 0.3943,  1.9608,  1.3240],
        [ 0.9882,  4.9523, -3.2607],
        [ 0.4077,  2.3038,  0.8229],
        [ 0.9691,  4.6598, -3.4778],
        [ 0.4375, -2.6062, -0.3117],
        [ 0.8200,  2.3939, -4.2982],
        [ 0.7378,  3.5193, -2.6855],
        [ 0.7539, -1.8208, -4.1405],
        [ 0.9815,  5.2771, -2.6138],
        [ 0.7960,  4.7647, -0.3310],
        [ 0.3931,  0.2931, -2.3402],
        [ 0.4438, -1.9463, -1.8168],
        [ 0.4292,  0.2800, -2.5597],
        [ 0.3528, -1.0778, -1.8220],
        [ 0.4517, -2.6399,  0.6134],
        [ 0.7353, -4.1689, -1.4431],
        [ 0.4050, -1.2918,  2.0584],
        [ 0.9499,  1.3712,  5.5322],
        [ 0.7441,  4.3627,  0.9476],
 

In [45]:
d = {}

for i in range(len(edge_ind[80][0])):
    if edge_ind[80][0, i].item() not in d:
        d[edge_ind[80][0, i].item()] = {}
    d[edge_ind[80][0, i].item()][edge_ind[80][1, i].item()] = edge_atr[80][i]
    #print(f'{edge_ind[80][0, i].item()} ---- {edge_ind[80][1, i].item()}')

In [50]:
print(d[1])
print(d[17])
print(d[92])

{17: tensor([ 0.5721, -0.4936,  3.3969]), 92: tensor([ 0.9019, -0.3360,  5.4007])}
{92: tensor([0.3350, 0.1576, 2.0039]), 1: tensor([ 0.5721,  3.3969, -0.4936]), 4: tensor([ 0.5749, -3.3533,  0.8082])}
{1: tensor([ 0.9019,  5.4007, -0.3360]), 4: tensor([ 0.2766, -1.3495,  0.9658]), 17: tensor([0.3350, 2.0039, 0.1576]), 33: tensor([ 0.8419, -4.8117, -1.5384])}
