In [3]:
import os
import sys
import numpy as np
import matplotlib.pyplot as plt

def path_link(path:str):
    sys.path.append(path)

path_link('master/code/lib')

import features as ft
import simulation as sim 
import simulation_2 as sim2
import simulation_3 as sim3
import NNSimulator as nnsim
import display as disp

from norm import normalizeCol


PATH_MODEL = 'master/code/models/'

In [2]:
def loadModel(modelName:str, inputShape:int = 9, edges_shape = 3, path = PATH_MODEL):
    """ 
    Function to import the model

    Args:
    -----
        - `modelName`: name of the model
        - `inputShape`: inout shape of the NN
        - `edges_shape`: edge shape of the NN
        - `path`: path where the models are
    """

    sys.path.append(path)

    loadFun = __import__(f'{modelName}', fromlist = ('loadNetwork'))

    model = loadFun.loadNetwork(inputShape, edges_shape)

    return model

In [3]:
# generate a simulation
data = sim.compute_main(100, (60, 3.5, 70, 0.5), 120, T = 450)[0]
id = 0

print(data)
print('------')

# get speeds
v = ft.getSpeeds(data)

print(data)
print('------')

mat = ft.getFeatures(data, np.array([0.1]))

print(data)
print('------')

featuresData = mat[0][id]

nextState = mat[1][id]

edge_ind, edge_atr = ft.getEdges(data)

print(data)
print('------')

edge_ind = edge_ind[id]
edge_atr = edge_atr[id]

v0:60, tau:3.5, k:70, epsilon:0.5


100%|██████████| 450/450 [00:02<00:00, 181.11it/s]


[[[  -8.1573174    -6.4755326 ]
  [   9.66396793   -2.96524812]
  [   8.8131778    -4.51966391]
  ...
  [  -9.40695045   -5.68911859]
  [   1.82371428  -11.02456058]
  [  -9.50501506    2.64205487]]

 [[  -8.23111945   -7.57543103]
  [  10.29463228   -2.13951389]
  [   8.08164686   -3.15661685]
  ...
  [  -9.16921477   -6.52926535]
  [   1.70224     -12.78473246]
  [  -9.65795068    2.69743454]]

 [[  -7.4991558    -8.54118601]
  [  10.71210177   -1.09801078]
  [   7.18703901   -2.58231467]
  ...
  [ -10.98964132   -7.68072485]
  [   2.36723656  -12.55471017]
  [  -8.44844697    1.99139034]]

 ...

 [[ -12.9491744    45.2416206 ]
  [  -6.74254686   15.47649296]
  [ -17.35398291   31.39113508]
  ...
  [  36.28354684   11.59503635]
  [ -69.42195621 -120.61919693]
  [ 114.23725485  -14.74766906]]

 [[ -13.08414061   45.86966556]
  [  -6.4843225    15.02081523]
  [ -16.98819004   30.91553485]
  ...
  [  36.86284785   11.75127444]
  [ -69.01225193 -121.05753744]
  [ 114.23655099  -14.751563

In [5]:
edge_atr = normalizeCol(edge_atr, -8, 8)

In [7]:
mod = loadModel('basic')

res = nnsim.getSimulationData(mod, 450, data, i = 5, display =True).detach().cpu().numpy()

100%|██████████| 450/450 [01:10<00:00,  6.35it/s]


In [10]:
print(data[5, :, :])

[[-6.70769103e+00 -1.20447869e+01]
 [ 1.05126102e+01  9.16556951e-03]
 [ 5.08645587e+00 -2.51541739e+00]
 [-2.69865476e+00 -1.29858681e+01]
 [ 8.27242511e+00  1.12751276e+00]
 [-6.59793326e+00 -9.53155954e+00]
 [-9.44567398e+00  1.18034040e+01]
 [-1.59306156e+01 -1.98064434e+00]
 [-8.90913792e+00 -3.16356179e+00]
 [-8.61803285e-01  1.16183888e+01]
 [-1.05127846e+01  9.26529602e+00]
 [-1.82755894e+00 -5.49528190e+00]
 [ 8.07868302e+00 -1.45302445e+01]
 [ 4.41288817e+00 -3.50812239e+00]
 [ 3.98322851e+00 -1.45643980e+01]
 [ 1.44258755e+01  5.63624055e+00]
 [ 1.01211154e+01  6.85418467e+00]
 [-4.58845192e+00 -6.71853780e+00]
 [ 4.49494055e+00  1.48081520e+01]
 [ 4.61975411e+00  9.86656547e+00]
 [ 1.24655621e+01 -8.65329300e+00]
 [ 1.37913769e+01  9.60998398e-01]
 [-8.42429163e+00 -4.69610273e+00]
 [-2.71727235e+00  1.06699758e+01]
 [-1.39119328e+00 -1.00865933e+01]
 [-1.80101678e+00  4.05754692e+00]
 [-9.20555319e+00 -9.77656635e+00]
 [ 4.45403301e+00 -7.53450166e+00]
 [-1.43469418e+01  2

In [11]:
print(res)

[[ -17.637074   -34.468464 ]
 [  12.645855   -24.779806 ]
 [ -73.591995   -41.801147 ]
 [ 105.25616    -64.955154 ]
 [  -4.8980923  -63.642067 ]
 [  64.049736  -112.51345  ]
 [  44.39856     29.49199  ]
 [ 118.67448    117.62885  ]
 [ -99.57403     46.4615   ]
 [ -42.703037  -107.915955 ]
 [ 118.27712    112.95832  ]
 [ -62.073837   -11.223586 ]
 [ -52.928574    10.736799 ]
 [-112.79412     -1.5042844]
 [  56.32201    -56.630035 ]
 [ -33.7959     -81.89634  ]
 [  49.552284   -77.65102  ]
 [  55.662872   -24.842676 ]
 [   3.4606662   88.436775 ]
 [ -42.145973  -105.06634  ]
 [-102.37067    -40.856346 ]
 [  76.71645     -7.1270614]
 [  83.688866    91.950096 ]
 [  82.81681   -112.99183  ]
 [ -64.85716     84.49478  ]
 [  78.147514  -100.371574 ]
 [  54.101494   -45.17993  ]
 [ -77.05769     93.379265 ]
 [ -32.78427    105.57599  ]
 [   8.869022   -21.739992 ]
 [  28.139732  -102.722466 ]
 [-108.74434     36.1055   ]
 [ -71.330635   -97.51662  ]
 [  22.49421   -105.94556  ]
 [  56.90641  

In [56]:
print(os.path.exists('/master/tests/data/vid_test.mp4'))
print(p)

True
/master/tests/data/vid_test.mp4


In [12]:
cwd = os.getcwd()
p = '/master/tests/data/vid_test.mp4'
vidParams = disp.videoParameters(p)

disp.create_simulation_video_cv2(res.copy(), vidParams, ((-140, 140), (-140, 140)))


In [4]:
cwd = os.getcwd()
p = '/master/tests/data/vid_test_d.mp4'
vidParams = disp.videoParameters(p)

disp.create_simulation_video_cv2(data[5:, :, :].copy(), vidParams, ((-140, 140), (-140, 140)))


### Get different kinds of simulations

In [6]:
nb = 80
v0 = [25, 60, 30, 7]
k = [25, 70, 50, 40]
tau = [2.5, 3.5, 2.5, 1.5]
epsilon = [0.5, 0.5, 0.5, 0.5]


path = '/master/tests/data/simulation_types'


for i in range(len(epsilon)):
    #data = sim.compute_main(nb, (v0[i], tau[i], k[i], epsilon[i]), 120, T = 1000)[0]
    data = sim2.compute_main(nb, (v0[i], tau[i], k[i], epsilon[i]), 120, T = 1000, seed=np.random.randint(1, 1015151231))[0]
    #data = sim3.compute_main(nb, (v0[i], tau[i], k[i], epsilon[i]), 120, T = 1000)[0]

    name = f"v0_{v0[i]}_tau_{tau[i]}_k_{k[i]}.mp4"

    p = os.path.join(path, name)
    vidParams = disp.videoParameters(p)

    disp.create_simulation_video_cv2(data.copy(), vidParams, ((-140, 140), (-140, 140)))


v0:25, tau:2.5, k:25, epsilon:0.5


100%|██████████| 1000/1000 [00:03<00:00, 263.17it/s]


v0:60, tau:3.5, k:70, epsilon:0.5


100%|██████████| 1000/1000 [00:02<00:00, 362.26it/s]


v0:30, tau:2.5, k:50, epsilon:0.5


100%|██████████| 1000/1000 [00:03<00:00, 268.33it/s]


v0:7, tau:1.5, k:40, epsilon:0.5


100%|██████████| 1000/1000 [00:06<00:00, 158.22it/s]
